AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla de CloudFormation para crear una instancia EC2

Parameters:
  ImageId:
    Description: ID de la imagen AMI para la instancia EC2
    Type: String
    Default: ami-0e2c8caa4b6378d8c

Resources:
  VPCNAT:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 11.0.0.0/20
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC_NAT

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCNAT
      CidrBlock: 11.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCNAT
      CidrBlock: 11.0.2.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet

  PublicSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Grupo de seguridad origen"
      VpcId: !Ref VPC_NAT
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Publica:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref ImageId
      KeyName: vockey
      SecurityGroupIds:
        - !Ref PublicSG
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: EC2_Publica



