AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla de CloudFormation para crear una instancia EC2

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e2c8caa4b6378d8c # Cambiar según la región
      KeyName: hockey
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance
